import { NextResponse } from 'next/server';

export const runtime = 'edge';

export async function POST(request: Request) {
  try {
    const { text, from = 'auto', to = 'drow' } = await request.json();

    if (!text) {
      return NextResponse.json({ error: 'No text provided' }, { status: 400 });
    }

    // 使用Drow语翻译逻辑进行翻译
    const translated = await translateToDrow(text);

    return NextResponse.json({
      translated: translated,
      originalText: text,
      from,
      to,
    });
  } catch (error) {
    console.error('Drow translation error:', error);
    return NextResponse.json({ error: 'Translation failed' }, { status: 500 });
  }
}

// Drow语翻译函数
async function translateToDrow(text: string): Promise<string> {
  try {
    // 模拟翻译延迟，提供更好的用户体验
    await new Promise((resolve) => setTimeout(resolve, 800));

    // Drow语言字典
    const drowDictionary: { [key: string]: string } = {
      a: 'dos',
      ability: 'dos',
      accepting: 'dos',
      accessible: 'dos',
      acquaintance: 'dos',
      active: 'dos',
      adaptable: 'dos',
      affected: 'dos',
      afterlife: 'dos',
      agreement: 'abbil',
      air: 'elghinn',
      ale: 'glaut',
      alone: 'wun',
      am: 'dos',
      an: 'dos',
      ancient: 'dos',
      and: 'bel',
      angel: 'abbil',
      answer: 'abbil',
      antarctic: 'abbil',
      antidote: 'dos',
      anywhere: 'dos',
      approach: 'dos',
      approached: 'dos',
      approximate: 'abbil',
      arctic: 'abbil',
      are: 'abbilen',
      area: 'dos',
      armor: 'wafae',
      arrival: 'dos',
      arrived: 'dos',
      arrow: 'uktar',
      assurance: 'kaas',
      attached: 'dos',
      authentic: 'dos',
      autonomy: 'dos',
      available: 'dos',
      axe: 'uktar',
      balance: 'abbil',
      barbarian: 'jal',
      be: 'dos',
      beach: 'abbil',
      became: 'dos',
      become: 'dos',
      becoming: 'dos',
      been: 'dos',
      beer: 'glaut',
      began: 'dos',
      begin: 'dos',
      beginning: 'dos',
      begun: 'dos',
      being: 'dos',
      belief: 'kaas',
      betray: 'zharess',
      bird: 'abbil',
      birthright: 'dos',
      blade: 'uktar',
      blended: 'dos',
      blood: 'ith',
      blunt: 'abbil',
      body: 'abbil',
      bond: 'dos',
      bone: 'abbil',
      bow: 'uktar',
      bread: 'abbil',
      bridge: 'dos',
      bright: 'tel',
      brightness: 'tel',
      brilliant: 'tel',
      bugbear: 'goblin',
      but: 'vel',
      butter: 'abbil',
      calm: 'abbil',
      came: 'dos',
      can: 'dos',
      capability: 'dos',
      captain: 'jal',
      care: 'dos',
      caution: 'dos',
      cautious: 'dos',
      centaur: 'goblin',
      center: 'dos',
      ceremony: 'dos',
      certainty: 'kaas',
      chamber: 'dos',
      changing: 'dos',
      cheese: 'abbil',
      child: 'abbil',
      city: 'ssussun',
      clarity: 'tel',
      clean: 'dos',
      cleric: 'jabbress',
      climate: 'abbil',
      close: 'dos',
      coincidence: 'abbil',
      combined: 'dos',
      come: 'dos',
      comedy: 'dos',
      comfort: 'abbil',
      coming: 'dos',
      common: 'dos',
      concord: 'abbil',
      confidence: 'kaas',
      connected: 'dos',
      connection: 'dos',
      consensus: 'abbil',
      content: 'dos',
      conviction: 'kaas',
      cooperative: 'dos',
      corridor: 'dos',
      cosmos: 'dos',
      could: 'dos',
      covered: 'dos',
      coward: 'abbil',
      cowardice: 'abbil',
      cowardly: 'abbil',
      cultural: 'dos',
      culture: 'dos',
      cure: 'dos',
      curved: 'dos',
      custom: 'dos',
      dagger: 'uktar',
      dark: 'il',
      darkness: 'il',
      dead: 'abbil',
      death: 'elghinn',
      defeat: 'abbil',
      defend: 'lueth',
      defended: 'dos',
      defense: 'lueth',
      delicate: 'dos',
      desert: 'abbil',
      design: 'dos',
      devoted: 'dos',
      dictator: 'ilharess',
      did: 'dos',
      diligent: 'dos',
      dim: 'il',
      disadvantage: 'abbil',
      discovered: 'dos',
      disease: 'abbil',
      divine: 'dos',
      do: 'dos',
      does: 'dos',
      doing: 'dos',
      domain: 'dos',
      domestic: 'dos',
      done: 'dos',
      doorway: 'dos',
      doubt: 'abbil',
      drink: 'glaut',
      drop: 'abbil',
      drug: 'dos',
      dryad: 'goblin',
      dull: 'il',
      dumb: 'abbil',
      durable: 'dos',
      dwarf: 'barren',
      dynamic: 'dos',
      early: 'dos',
      earth: 'dos',
      edge: 'uktar',
      effective: 'dos',
      efficient: 'dos',
      egg: 'abbil',
      emperor: 'ilharess',
      empress: 'ilharess',
      enemy: 'bauth',
      entrance: 'dos',
      entry: 'dos',
      escape: 'dos',
      escaped: 'dos',
      estimate: 'abbil',
      everywhere: 'dos',
      existence: 'dos',
      exposed: 'dos',
      fail: 'abbil',
      failure: 'abbil',
      fairy: 'goblin',
      faith: 'kaas',
      faithful: 'dos',
      fake: 'abbil',
      fall: 'abbil',
      false: 'abbil',
      family: 'abbilen',
      fantasy: 'dos',
      farm: 'abbil',
      fat: 'abbil',
      fear: 'abbil',
      feel: 'zhaun',
      feeling: 'dos',
      felt: 'dos',
      field: 'abbil',
      fighter: 'jal',
      find: 'quar',
      fine: 'dos',
      first: 'dos',
      fish: 'abbil',
      flat: 'dos',
      flexible: 'dos',
      flower: 'abbil',
      folklore: 'dos',
      food: 'abbil',
      fool: 'abbil',
      forbearing: 'dos',
      forest: 'abbil',
      found: 'quar',
      free: 'dos',
      freedom: 'dos',
      fresh: 'dos',
      friendly: 'dos',
      fruit: 'abbil',
      fused: 'dos',
      galaxy: 'dos',
      gateway: 'dos',
      gave: 'dos',
      gentle: 'dos',
      genuine: 'dos',
      get: 'quar',
      getting: 'quar',
      give: 'dos',
      given: 'dos',
      giving: 'dos',
      gloom: 'il',
      gloomy: 'il',
      go: 'dos',
      goblin: 'goblin',
      goddess: 'ilharess',
      going: 'dos',
      gone: 'dos',
      good: 'dos',
      goodness: 'dos',
      got: 'quar',
      gotten: 'quar',
      grace: 'dos',
      gradual: 'dos',
      grief: 'abbil',
      guard: 'jal',
      guarded: 'dos',
      guess: 'abbil',
      habit: 'dos',
      had: 'dos',
      hallway: 'dos',
      hardworking: 'dos',
      harmony: 'abbil',
      has: 'dos',
      hate: 'bauth',
      have: 'dos',
      having: 'dos',
      he: 'jal',
      heal: 'dos',
      health: 'abbil',
      hear: 'zhaun',
      heart: 'abbil',
      heaven: 'dos',
      hello: 'usstan',
      helmet: 'wafae',
      helpful: 'dos',
      helpless: 'abbil',
      her: 'dos',
      herb: 'abbil',
      here: 'dos',
      heritage: 'dos',
      hers: 'dos',
      herself: 'dos',
      hidden: 'wun',
      hide: 'wun',
      him: 'jal',
      himself: 'dos',
      his: 'dos',
      history: 'dos',
      hobgoblin: 'goblin',
      home: 'oloth',
      honest: 'dos',
      honey: 'abbil',
      how: 'dos',
      human: 'jal',
      humility: 'abbil',
      i: 'usstan',
      idiot: 'abbil',
      if: 'dos',
      ignore: 'abbil',
      illumination: 'tel',
      immediate: 'dos',
      imp: 'goblin',
      impacted: 'dos',
      incorrect: 'abbil',
      independence: 'dos',
      individual: 'dos',
      inferior: 'abbil',
      influenced: 'dos',
      inheritance: 'dos',
      innocence: 'dos',
      insecurity: 'abbil',
      invisibility: 'wun',
      invisible: 'wun',
      is: 'dos',
      island: 'abbil',
      it: 'dos',
      its: 'dos',
      itself: 'dos',
      joined: 'dos',
      jungle: 'abbil',
      karma: 'dos',
      keep: 'dos',
      keeping: 'dos',
      kept: 'dos',
      kind: 'dos',
      king: 'jal',
      knife: 'uktar',
      knight: 'jal',
      kobold: 'goblin',
      lack: 'abbil',
      lady: 'ilharess',
      lake: 'glaut',
      lasting: 'dos',
      later: 'dos',
      leader: 'ilharess',
      legacy: 'dos',
      leisurely: 'dos',
      lenient: 'dos',
      let: 'dos',
      letting: 'dos',
      level: 'dos',
      liberated: 'dos',
      liberation: 'dos',
      liberty: 'dos',
      lie: 'abbil',
      life: 'abbil',
      light: 'tel',
      like: 'dos',
      liked: 'dos',
      link: 'dos',
      linked: 'dos',
      listen: 'zhaun',
      living: 'dos',
      local: 'dos',
      lonely: 'wun',
      look: 'zhaun',
      lord: 'jal',
      lose: 'abbil',
      loss: 'abbil',
      loyal: 'dos',
      luminous: 'tel',
      master: 'ilharess',
      may: 'dos',
      me: 'usstan',
      mead: 'glaut',
      meaning: 'dos',
      meat: 'abbil',
      medicine: 'abbil',
      merged: 'dos',
      method: 'dos',
      microscopic: 'abbil',
      middle: 'dos',
      might: 'dos',
      mild: 'dos',
      milk: 'glaut',
      mine: 'dos',
      minotaur: 'goblin',
      miss: 'abbil',
      missing: 'abbil',
      mixed: 'dos',
      modern: 'dos',
      modesty: 'dos',
      monk: 'jal',
      monochrome: 'abbil',
      moon: 'dos',
      mortal: 'dos',
      mother: 'ilth',
      mountain: 'abbil',
      mourning: 'abbil',
      murk: 'il',
      muscle: 'abbil',
      must: 'dos',
      muted: 'abbil',
      my: 'dos',
      myself: 'dos',
      mystery: 'wun',
      native: 'dos',
      near: 'dos',
      neighbor: 'dos',
      neutral: 'abbil',
      new: 'dos',
      nice: 'dos',
      night: 'usstan',
      no: 'nau',
      notice: 'zhaun',
      now: 'dos',
      nymph: 'goblin',
      obscurity: 'il',
      observe: 'zhaun',
      obviousness: 'tel',
      ocean: 'glaut',
      ogre: 'goblin',
      old: 'dos',
      open: 'dos',
      opened: 'dos',
      or: 'vel',
      orc: 'goblin',
      ordinary: 'dos',
      original: 'dos',
      ought: 'dos',
      our: 'dos',
      ours: 'dos',
      ourselves: 'dos',
      pain: 'abbil',
      paladin: 'jabbress',
      paradise: 'dos',
      passage: 'dos',
      past: 'dos',
      patient: 'dos',
      pattern: 'dos',
      'pay attention': 'zhaun',
      peace: 'abbil',
      people: 'abbilen',
      pepper: 'abbil',
      perception: 'zhaun',
      performance: 'dos',
      permanent: 'dos',
      personal: 'dos',
      pixie: 'goblin',
      plan: 'dos',
      planet: 'dos',
      plant: 'abbil',
      point: 'uktar',
      poise: 'dos',
      poor: 'abbil',
      portal: 'dos',
      poverty: 'abbil',
      precaution: 'dos',
      prefer: 'dos',
      prehistory: 'dos',
      present: 'dos',
      prevention: 'dos',
      priest: 'jabbress',
      priestess: 'ilharess',
      primary: 'dos',
      prince: 'jalil',
      princess: 'ilharess',
      pristine: 'dos',
      private: 'dos',
      productive: 'dos',
      prompt: 'dos',
      protect: 'lueth',
      protected: 'dos',
      protection: 'lueth',
      providence: 'dos',
      public: 'dos',
      punctual: 'dos',
      pure: 'dos',
      purity: 'dos',
      purpose: 'dos',
      queen: 'ilharess',
      quiet: 'wun',
      radiant: 'tel',
      rain: 'glaut',
      ranger: 'jal',
      reached: 'dos',
      realm: 'dos',
      reason: 'dos',
      rebirth: 'dos',
      region: 'dos',
      reincarnation: 'dos',
      relationship: 'dos',
      relaxation: 'abbil',
      release: 'abbil',
      reliance: 'dos',
      relief: 'abbil',
      remaining: 'dos',
      remedy: 'dos',
      rescued: 'dos',
      resolution: 'abbil',
      rest: 'abbil',
      resurrection: 'dos',
      revealed: 'dos',
      right: 'dos',
      ritual: 'dos',
      river: 'glaut',
      rogue: 'wun',
      room: 'dos',
      rounded: 'dos',
      routine: 'dos',
      ruler: 'ilharess',
      sadness: 'abbil',
      safe: 'dos',
      safety: 'abbil',
      salt: 'abbil',
      satyr: 'goblin',
      saved: 'dos',
      saw: 'zhaun',
      sea: 'glaut',
      search: 'zhaun',
      secret: 'wun',
      secure: 'dos',
      security: 'lueth',
      see: 'zhaun',
      seeing: 'zhaun',
      seek: 'zhaun',
      seem: 'dos',
      seemed: 'dos',
      seeming: 'dos',
      seen: 'zhaun',
      sense: 'zhaun',
      serenity: 'abbil',
      shadow: 'waelin',
      shadowy: 'il',
      shall: 'dos',
      she: 'il',
      shield: 'wafae',
      shielded: 'dos',
      shining: 'tel',
      short: 'abbil',
      should: 'dos',
      sickness: 'abbil',
      silent: 'wun',
      simplicity: 'dos',
      sincere: 'dos',
      sit: 'abbil',
      skepticism: 'abbil',
      skill: 'dos',
      skin: 'abbil',
      sky: 'dos',
      slave: 'jaluk',
      sleep: 'abbil',
      small: 'abbil',
      smell: 'zhaun',
      smooth: 'dos',
      snow: 'abbil',
      social: 'dos',
      societal: 'dos',
      soft: 'dos',
      'solar system': 'dos',
      soldier: 'jal',
      solid: 'dos',
      solitude: 'wun',
      solution: 'abbil',
      somewhere: 'dos',
      son: 'jalil',
      soon: 'dos',
      sorrow: 'abbil',
      space: 'dos',
      spear: 'uktar',
      spice: 'abbil',
      spider: 'wafae',
      sprite: 'goblin',
      stable: 'dos',
      stage: 'dos',
      star: 'dos',
      start: 'dos',
      started: 'dos',
      starting: 'dos',
      staying: 'dos',
      stealth: 'wun',
      sterile: 'dos',
      straight: 'dos',
      strategy: 'dos',
      student: 'abbil',
      stupidity: 'abbil',
      sturdy: 'dos',
      subtlety: 'wun',
      suffering: 'abbil',
      sugar: 'abbil',
      sun: 'dos',
      survival: 'dos',
      swamp: 'abbil',
      sword: 'uktar',
      tactics: 'dos',
      take: 'quar',
      taken: 'quar',
      taking: 'quar',
      talent: 'dos',
      taste: 'zhaun',
      technique: 'dos',
      temperate: 'abbil',
      territory: 'dos',
      that: 'dos',
      the: 'dos',
      theater: 'dos',
      their: 'dos',
      theirs: 'dos',
      them: 'abbilen',
      themselves: 'dos',
      then: 'dos',
      there: 'dos',
      these: 'abbilen',
      they: 'abbilen',
      thick: 'abbil',
      thief: 'wun',
      thin: 'abbil',
      this: 'dos',
      those: 'abbilen',
      tie: 'dos',
      timidity: 'abbil',
      tiny: 'abbil',
      tip: 'uktar',
      tired: 'abbil',
      tolerant: 'dos',
      took: 'quar',
      touch: 'zhaun',
      touched: 'dos',
      town: 'ssussun',
      tradition: 'dos',
      traditional: 'dos',
      tranquility: 'abbil',
      transparency: 'dos',
      treat: 'dos',
      tree: 'abbil',
      tried: 'dos',
      troll: 'goblin',
      tropical: 'abbil',
      trust: 'kaas',
      truthful: 'dos',
      try: 'dos',
      trying: 'dos',
      tundra: 'abbil',
      tyrant: 'ilharess',
      uncertainty: 'abbil',
      unconscious: 'abbil',
      uncovered: 'dos',
      universe: 'dos',
      unknown: 'wun',
      unlocked: 'dos',
      unpackaged: 'dos',
      unremarkable: 'dos',
      unsealed: 'dos',
      untouched: 'dos',
      unwrapped: 'dos',
      us: 'usstan',
      useful: 'dos',
      village: 'abbil',
      virgin: 'dos',
      virtue: 'dos',
      virtuous: 'dos',
      visibility: 'tel',
      voluntary: 'dos',
      warrior: 'jal',
      was: 'dos',
      watch: 'zhaun',
      water: 'glaut',
      we: 'usstan',
      weak: 'abbil',
      weakness: 'abbil',
      weapon: 'uktar',
      weather: 'abbil',
      welcoming: 'dos',
      went: 'dos',
      were: 'abbilen',
      what: 'dos',
      when: 'dos',
      where: 'dos',
      which: 'dos',
      who: 'dos',
      whom: 'dos',
      whose: 'dos',
      why: 'dos',
      will: 'dos',
      wine: 'glaut',
      world: 'dos',
      worse: 'abbil',
      worst: 'abbil',
      would: 'dos',
      wrong: 'abbil',
      yes: 'ussta',
      you: 'usstan',
      young: 'dos',
      your: 'dos',
      yours: 'dos',
      yourself: 'dos',
      yourselves: 'dos',
      zone: 'dos',
    };

    // 增强的翻译逻辑，提供更好的映射
    const translated = text
      .split(' ')
      .map((word) => {
        // 保留原始标点符号和大小写
        const punctuation = word.match(/[.,!?;:'"(){}[\]]*$/)?.[0] || '';
        const cleanWord = word.replace(/[.,!?;:'"(){}[\]]*$/g, '');
        const isCapitalized = cleanWord[0] === cleanWord[0]?.toUpperCase();
        const isAllCaps = cleanWord === cleanWord.toUpperCase();
        const lowerWord = cleanWord.toLowerCase();

        // 首先尝试精确匹配
        let translation = drowDictionary[lowerWord];

        // 如果没有精确匹配，尝试部分匹配和相似词
        if (!translation) {
          // 检查带有常见后缀的词
          for (const [key, value] of Object.entries(drowDictionary)) {
            if (lowerWord.includes(key) || key.includes(lowerWord)) {
              translation = value;
              break;
            }
          }
        }

        // 如果仍然没有翻译，尝试常见模式
        if (!translation) {
          // Drow语的常见模式
          const patterns = [
            { pattern: /ing$/, replacement: 'doom' },
            { pattern: /ed$/, replacement: 'dos' },
            { pattern: /s$/, replacement: 'en' },
            { pattern: /tion$/, replacement: 'abbil' },
            { pattern: /ment$/, replacement: 'dos' },
          ];

          for (const { pattern, replacement } of patterns) {
            if (pattern.test(lowerWord)) {
              translation = lowerWord.replace(pattern, replacement);
              break;
            }
          }
        }

        // 回退：添加Drow风格后缀
        if (!translation) {
          const drowSuffixes = [
            'dos',
            'abbil',
            'il',
            'kaas',
            'bel',
            'vel',
            'wun',
            'zhaun',
          ];
          const suffix =
            drowSuffixes[Math.floor(Math.random() * drowSuffixes.length)];
          translation = lowerWord + suffix;
        }

        // 恢复大小写
        if (isAllCaps) {
          translation = translation.toUpperCase();
        } else if (isCapitalized) {
          translation =
            translation.charAt(0).toUpperCase() + translation.slice(1);
        }

        return translation + punctuation;
      })
      .join(' ');

    return translated;
  } catch (error) {
    console.error('Drow translation service error:', error);
    throw new Error('Translation service unavailable');
  }
}
