// Routes configuration for navigation
export const Routes = {
  // Fun Translate routes
  AlienTextGenerator: '/alien-text-generator',
  BabyTranslator: '/baby-translator',
  BadTranslator: '/bad-translator',
  DogTranslator: '/dog-translator',
  DumbItDownAI: '/dumb-it-down-ai',
  GenAlphaTranslator: '/gen-alpha-translator',
  GenZTranslator: '/gen-z-translator',
  GibberishTranslator: '/gibberish-translator',
  PigLatinTranslator: '/pig-latin-translator',
  VerboseGenerator: '/verbose-generator',

  // Game Translator routes
  AlBhedTranslator: '/al-bhed-translator',
  DrowTranslator: '/drow-translator',
  GasterTranslator: '/gaster-translator',
  HighValyrianTranslator: '/high-valyrian-translator',
  MandalorianTranslator: '/mandalorian-translator',
  MinionTranslator: '/minion-translator',
  RuneTranslator: '/rune-translator',
  RunicTranslator: '/runic-translator',
  WingdingsTranslator: '/wingdings-translator',
  YodaTranslator: '/yoda-translator',

  // Language Translator routes
  AlbanianToEnglish: '/albanian-to-english',
  AncientGreekTranslator: '/ancient-greek-translator',
  AramaicTranslator: '/aramaic-translator',
  BaybayinTranslator: '/baybayin-translator',
  CantoneseTranslator: '/cantonese-translator',
  ChineseToEnglishTranslator: '/chinese-to-english-translator',
  CreoleToEnglishTranslator: '/creole-to-english-translator',
  CuneiformTranslator: '/cuneiform-translator',
  EnglishToAmharicTranslator: '/english-to-amharic-translator',
  EnglishToChineseTranslator: '/english-to-chinese-translator',
  EnglishToPersianTranslator: '/english-to-persian-translator',
  EnglishToPolishTranslator: '/english-to-polish-translator',
  EnglishToSwahiliTranslator: '/english-to-swahili-translator',
  EsperantoTranslator: '/esperanto-translator',
  GreekTranslator: '/greek-translator',
  HaitianCreoleTranslator: '/haitian-creole-translator',
  IvrTranslator: '/ivr-translator',
  JapaneseToEnglishTranslator: '/japanese-to-english-translator',
  EnglishToTurkishTranslator: '/english-to-turkish-translator',
  MangaTranslator: '/manga-translator',
  MiddleEnglishTranslator: '/middle-english-translator',
  NahuatlTranslator: '/nahuatl-translator',
  OghamTranslator: '/ogham-translator',
  SamoanToEnglishTranslator: '/samoan-to-english-translator',
  SwahiliToEnglishTranslator: '/swahili-to-english-translator',
  TeluguToEnglishTranslator: '/telugu-to-english-translator',
  JamaicanTranslator: '/jamaican-translator',
  NumbersToLetters: '/numbers-to-letters',
  BrailleTranslator: '/braille-translator',
  DraconicTranslator: '/draconic-translator',
  MorseCodeTranslator: '/morse-code-translator',

  // Static pages
  Home: '/',
  About: '/about',
  Privacy: '/privacy',
  Terms: '/terms',
} as const;
